# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "**/*_test.go"
  - "**/testutil/**"
  - "**/examples/**"
  - "**/scripts/**"
  - "**/*.pb.go"
  - "**/vendor/**"
  - "**/mocks/**"